# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES=" "
RUST_MIN_VER="1.86.0"

inherit cargo

ECARGO_OFFLINE=1

DESCRIPTION="Command-line interface for Wasmtime"
HOMEPAGE="https://wasmtime.dev"
SRC_URI="https://github.com/bytecodealliance/wasmtime/releases/download/v${PV}/wasmtime-v${PV}-src.tar.gz"

LICENSE="Apache-2.0-with-LLVM-exceptions"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD CC0-1.0 ISC MIT
	MPL-2.0 MPL-2.0 Unicode-3.0 Unicode-DFS-2016 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"

DEPEND="
	app-arch/zstd:=
"
RDEPEND="${DEPEND}"
BDEPEND=""

src_prepare() {
	default

	rmdir "${WORKDIR}/${P}" || die 'could not clear target src dir'
	ln -s "${WORKDIR}/wasmtime-v${PV}-src" "${WORKDIR}/${P}" || die 'could not symlink src'
	ln -s "${WORKDIR}/${P}/vendor/"* "${CARGO_HOME}/gentoo" || die 'could not symlink vendor'
}

src_configure() {
	cargo_src_configure --all-features
}

src_install() {
	dobin "$(cargo_target_dir)/wasmtime"
}

src_test() {
	RUST_BACKTRACE=full cargo_src_test -p wasmtime
}

pkg_postinst() {
	ewarn 'Only the tests for the wasmtime crate have been run,'
	ewarn 'which is a very small subset of the entire suite.'
	ewarn
	ewarn 'If you heavily rely on wasmtime it is recommended to'
	ewarn 'install the wasm32-wasip1 and wasm32-unknown-unknown'
	ewarn 'targets for your Rust toolchain und test yourself:'
	ewarn
	ewarn "cd ${WORKDIR}/${P}"
	ewarn "cargo test"
	ewarn
}
